linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gocyclo
    - golint
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
