name: libovsb-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      openvswitch:
        image: socketplane/openvswitch:2.4.0
        ports:
        - 6640/tcp

    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.39

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -race -v -coverprofile=profile.cov ./...
      env:
        OVS_HOST: localhost
        OVS_PORT: ${{ job.services.openvswitch.ports[6640] }}
        
    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
