name: libovsb-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ovs_version:
          - latest
          - 2.15.0
          - 2.14.0
          - 2.13.0

    services:
      ovs:
        image: libovsdb/ovs:${{ matrix.ovs_version }}
        options: --tty
        ports:
          - 6640:6640

    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.39

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -race -v -coverprofile=profile.cov ./...
      env:
        OVS_DB: tcp:127.0.0.1:6640

    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
